USE hr;

SELECT 
    M.EMPLOYEE_ID,
    M.FIRST_NAME,
    M.JOB_ID,
    COUNT(E.EMPLOYEE_ID) AS MANAGED_EMPLOYEE_COUNT
FROM EMPLOYEES M
JOIN EMPLOYEES E ON M.EMPLOYEE_ID = E.MANAGER_ID
GROUP BY M.EMPLOYEE_ID, M.FIRST_NAME, M.JOB_ID
HAVING COUNT(CASE WHEN E.JOB_ID != M.JOB_ID THEN 1 END) = 0;