const age = parseInt('50f');
const weight = parseInt('9twenty');
const address = parseInt('tom60');
console.log(age, weight, address);
let num1 = 3.14159;
num1 = parseInt(num1);
console.log(num1);
const premikboy = 'Premik';
console.log(typeof premikboy);
const num2 = '56.78';
const num3 = '12.34';
const sum = (parseFloat(num2) + parseFloat(num3)).toString();
console.log(sum);
console.log(typeof sum);
let num = 6;
let text = num.toString(2);
console.log(text);
const num4 = 4;
let text2 = num4.toString(2);
text3 = (parseInt(text2, 2) + parseInt(text2, 2)).toString(2);
console.log(text3);
console.log(typeof text3);