USE hr;

SELECT
    d.DEPARTMENT_ID,
    d.DEPARTMENT_NAME,
    dept_avg.AVG_Salary,
    SUM(CASE WHEN e.SALARY >= dept_avg.AVG_SALARY THEN 1 ELSE 0 END) /
    SUM(CASE WHEN e.SALARY <= dept_avg.AVG_SALARY THEN 1 ELSE 0 END) AS RATIO
FROM DEPARTMENTS d
JOIN EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
JOIN (
    SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
) dept_avg ON d.DEPARTMENT_ID = dept_avg.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID, d.DEPARTMENT_NAME, dept_avg.AVG_SALARY
ORDER BY d.DEPARTMENT_ID;
