USE hr;

SELECT
    CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS EMPLOYEE,
    CONCAT(m.FIRST_NAME, ' ', m.LAST_NAME) AS MANAGER,
    e.SALARY
FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
WHERE e.SALARY = (
    SELECT MAX(e2.SALARY)
    FROM EMPLOYEES e2
    WHERE e2.MANAGER_ID = e.MANAGER_ID
)
ORDER BY EMPLOYEE;