USE hr;

SELECT 
    CONCAT(
        CASE WHEN COMMISSION_PCT IS NOT NULL THEN 1 ELSE 0 END,
        CASE WHEN COMMISSION_PCT IS NOT NULL THEN ' (YES)' ELSE ' (NO)' END 
    ) AS 'IS_COMMISSION_PROVIDED?',
    COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY CASE WHEN COMMISSION_PCT IS NOT NULL THEN 1 ELSE 0 END;
